{{- define "imagePullSecret" }}
{{- with .Values.global.registry -}}
{{- $auth := printf "%s:%s" .username .password | b64enc -}}
{{- printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .host $auth  | b64enc -}}
{{- end -}}
{{- end -}}

{{- if .Values.global.imagePullSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade, pre-delete"
    "helm.sh/hook-weight": "-70"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
