"""
GenerateReportProcessor for Cyoda Client Application

Generates formatted report content from analysis results.
Creates email-ready report content according to workflow requirements.
"""

import logging
from datetime import datetime, timezone
from typing import Any, Dict

from common.entity.entity_casting import cast_entity
from common.processor.base import CyodaEntity, CyodaProcessor
from application.entity.report.version_1.report import Report
from application.entity.dataanalysis.version_1.dataanalysis import DataAnalysis
from services.services import get_entity_service


class GenerateReportProcessor(CyodaProcessor):
    """
    Processor for Report that generates formatted report content.
    Creates email-ready content from analysis results.
    """

    def __init__(self) -> None:
        super().__init__(
            name="generate_report",
            description="Generates formatted report content from analysis results",
        )
        self.logger: logging.Logger = getattr(
            self, "logger", logging.getLogger(__name__)
        )

    async def process(self, entity: CyodaEntity, **kwargs: Any) -> CyodaEntity:
        """
        Generate report content from the referenced DataAnalysis.

        Args:
            entity: The Report entity to process
            **kwargs: Additional processing parameters

        Returns:
            The processed entity with generated report content
        """
        try:
            self.logger.info(
                f"Starting report generation for Report {getattr(entity, 'technical_id', '<unknown>')}"
            )

            # Cast the entity to Report for type-safe operations
            report = cast_entity(entity, Report)

            # Get the referenced DataAnalysis
            entity_service = get_entity_service()
            analysis_response = await entity_service.get_by_id(
                entity_id=report.analysis_id,
                entity_class=DataAnalysis.ENTITY_NAME,
                entity_version=str(DataAnalysis.ENTITY_VERSION),
            )

            if not analysis_response:
                raise ValueError(f"DataAnalysis {report.analysis_id} not found")

            analysis = cast_entity(analysis_response.data, DataAnalysis)

            # Generate report content based on analysis results
            report_content = await self._generate_report_content(analysis)

            # Update report entity with content
            report.set_report_content(report_content)

            self.logger.info(
                f"Report {report.technical_id} content generated successfully"
            )

            return report

        except Exception as e:
            self.logger.error(
                f"Error generating report for Report {getattr(entity, 'technical_id', '<unknown>')}: {str(e)}"
            )
            raise

    async def _generate_report_content(self, analysis: DataAnalysis) -> str:
        """Generate formatted report content from analysis results"""
        try:
            current_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

            # Start building the report
            report_lines = [
                "London Houses Data Analysis Report",
                "=" * 40,
                "",
                f"Generated on: {current_time}",
                f"Analysis Type: {analysis.analysis_type.title()}",
                f"Analysis ID: {analysis.technical_id or analysis.entity_id}",
                "",
                "ANALYSIS SUMMARY",
                "-" * 20,
            ]

            # Add results section
            if analysis.results:
                report_lines.extend(self._format_results_section(analysis.results))

            # Add metrics section
            if analysis.metrics:
                report_lines.extend(self._format_metrics_section(analysis.metrics))

            # Add insights section
            report_lines.extend(self._generate_insights_section(analysis))

            # Add footer
            report_lines.extend(
                [
                    "",
                    "=" * 40,
                    "This report was automatically generated by the Cyoda Data Analysis System.",
                    "For questions or support, please contact your system administrator.",
                ]
            )

            return "\n".join(report_lines)

        except Exception as e:
            self.logger.error(f"Error generating report content: {str(e)}")
            raise

    def _format_results_section(self, results: Dict[str, Any]) -> list[str]:
        """Format the results section of the report"""
        lines = ["", "RESULTS", "-" * 10]

        if "total_records" in results:
            lines.append(f"Total Records Analyzed: {results['total_records']:,}")

        if "columns" in results:
            lines.append(f"Data Columns: {len(results['columns'])}")
            lines.append(
                f"Column Names: {', '.join(results['columns'][:5])}"
            )  # Show first 5
            if len(results["columns"]) > 5:
                lines.append(f"... and {len(results['columns']) - 5} more")

        if "price_stats" in results:
            price_stats = results["price_stats"]
            if "mean" in price_stats:
                lines.append(f"Average Price: £{price_stats['mean']:,.2f}")
            if "min" in price_stats and "max" in price_stats:
                lines.append(
                    f"Price Range: £{price_stats['min']:,.2f} - £{price_stats['max']:,.2f}"
                )

        # Add categorical data summaries
        for key, value in results.items():
            if key.endswith("_counts") and isinstance(value, dict):
                category_name = key.replace("_counts", "").replace("_", " ").title()
                lines.append(f"Top {category_name}:")
                for item, count in list(value.items())[:3]:  # Show top 3
                    lines.append(f"  - {item}: {count}")

        return lines

    def _format_metrics_section(self, metrics: Dict[str, Any]) -> list[str]:
        """Format the metrics section of the report"""
        lines = ["", "KEY METRICS", "-" * 15]

        if "avg_price" in metrics:
            lines.append(f"Average Property Price: £{metrics['avg_price']:,.2f}")

        if "price_range" in metrics:
            price_range = metrics["price_range"]
            lines.append(
                f"Price Range: £{price_range[0]:,.2f} - £{price_range[1]:,.2f}"
            )

        if "record_count" in metrics:
            lines.append(f"Total Properties: {metrics['record_count']:,}")

        if "data_quality" in metrics:
            lines.append(f"Data Quality: {metrics['data_quality'].title()}")

        return lines

    def _generate_insights_section(self, analysis: DataAnalysis) -> list[str]:
        """Generate insights based on analysis type and results"""
        lines = ["", "KEY INSIGHTS", "-" * 15]

        if analysis.analysis_type == "summary":
            lines.extend(
                [
                    "• This summary analysis provides an overview of the dataset structure",
                    "• Data completeness and basic statistics have been calculated",
                    "• Use this information to understand the scope of your data",
                ]
            )
        elif analysis.analysis_type == "statistical":
            lines.extend(
                [
                    "• Statistical analysis reveals price distributions and correlations",
                    "• Property values show variation across different categories",
                    "• Consider market trends when interpreting these statistics",
                ]
            )
        elif analysis.analysis_type == "trend":
            lines.extend(
                [
                    "• Trend analysis identifies patterns in the data over time",
                    "• Market dynamics can be observed through temporal patterns",
                    "• Use these insights for forecasting and planning",
                ]
            )

        # Add data-driven insights if available
        if analysis.results and "total_records" in analysis.results:
            record_count = analysis.results["total_records"]
            if record_count > 1000:
                lines.append("• Large dataset provides robust statistical foundation")
            elif record_count > 100:
                lines.append("• Moderate dataset size suitable for analysis")
            else:
                lines.append(
                    "• Limited dataset - consider gathering more data for better insights"
                )

        return lines
